FROM gradle:8.3.0-jdk17-jammy AS TEMP_BUILD_IMAGE
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN ./gradlew build --no-daemon

# App container
FROM eclipse-temurin:17-jdk-jammy
ENV ARTIFACT_NAME=account-0.0.1-SNAPSHOT.jar
ENV APP_HOME=/home/gradle/src

WORKDIR $APP_HOME/
COPY --from=TEMP_BUILD_IMAGE $APP_HOME/build/libs/$ARTIFACT_NAME .

EXPOSE 8082
ENTRYPOINT exec java -jar ${ARTIFACT_NAME}